#!/usr/bin/env python

"""
rst2md.py
======

This module provides a simple command line interface that uses the
Markdown writer to output from reStructuredText source.
"""

import locale
try:
    locale.setlocale(locale.LC_ALL, '')
except:
    pass

from docutils.core import publish_cmdline, default_description

from rst2md import markdown

description = ('Generates Markdown formatted text from standalone '
               'reStructuredText sources.  ' + default_description)

publish_cmdline(writer=markdown.Writer(), description=description)
